services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: mycrm
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: secure-prod-password
      MYSQL_ROOT_PASSWORD: was13579
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  mycrm-backend:
    image: mycrm-backend:v0.7.1
    container_name: django_backend
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    restart: always

volumes:
  mysql_data: