# Generated by Django 5.2 on 2025-09-24 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='阶段名称')),
                ('order', models.PositiveSmallIntegerField(unique=True, verbose_name='排序')),
                ('description', models.TextField(blank=True, verbose_name='阶段描述')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('source', models.CharField(choices=[('website', '官网咨询'), ('phone_call', '电话拜访'), ('referral', '客户推荐'), ('sales_assignment', '销售主管分配'), ('self_generated', '自行开发'), ('other', '其他')], default='self_generated', max_length=50, verbose_name='项目线索来源')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('expected_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预估销售额')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='预计成交日期')),
                ('actual_close_date', models.DateField(blank=True, null=True, verbose_name='实际成交日期')),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际成交金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='customer.customer', verbose_name='关联客户')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人')),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_in_stage', to='project.projectstage', verbose_name='当前阶段')),
            ],
        ),
    ]
