# Generated by Django 5.2 on 2025-09-24 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', '电话'), ('visit', '拜访'), ('email', '邮件'), ('meeting', '会议'), ('demo', '产品演示'), ('proposal', '提交方案'), ('other', '其他')], default='call', max_length=50, verbose_name='行动类型')),
                ('description', models.TextField(verbose_name='行动详情')),
                ('activity_date', models.DateTimeField(verbose_name='行动日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='project.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '行动记录',
                'verbose_name_plural': '行动记录',
                'ordering': ['-activity_date'],
            },
        ),
    ]
