# Generated by Django 5.2 on 2025-10-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='actual_close_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='actual_revenue',
        ),
        migrations.RemoveField(
            model_name='project',
            name='expected_close_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='expected_revenue',
        ),
        migrations.AddField(
            model_name='project',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='成交日期'),
        ),
        migrations.AddField(
            model_name='project',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='销售额'),
        ),
    ]
